"""Database creation

Revision ID: 9f20c91ae57b
Revises: 
Create Date: 2023-03-27 22:54:31.054586

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9f20c91ae57b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
                    sa.Column('title_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('title_id')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=254), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('task_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.title_id'], ),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
