"""Rename user_id as user

Revision ID: f6a66f730cdc
Revises: 28702e9ff40e
Create Date: 2023-03-29 22:38:28.289105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a66f730cdc'
down_revision = '28702e9ff40e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_user_id_fkey', 'task', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
